service: my-spa
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1

plugins:
  - serverless-s3-sync

custom:
  siteBucket: dp-spa-${sls:stage}
  s3Sync:
    - bucketName: s3-${self:custom.siteBucket}-${aws:accountId}
      localDir: build

resources:
  Resources:
    SpaBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: s3-${self:custom.siteBucket}-${aws:accountId}
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerEnforced
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          IgnorePublicAcls: true
          BlockPublicPolicy: false
          RestrictPublicBuckets: false

    SpaBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref SpaBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: !Sub "${SpaBucket.Arn}/*"

    SpaCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          DefaultRootObject: index.html
          Origins:
            - DomainName:
                Fn::GetAtt: [SpaBucket, DomainName]
              Id: SpaS3Origin
              S3OriginConfig: {}
          DefaultCacheBehavior:
            TargetOriginId: SpaS3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: false
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
  Outputs:
    WebsiteURL:
      Description: "CloudFront URL to access the SPA REACT"
      Value: !Sub "https://${SpaCloudFrontDistribution.DomainName}"   
outputs:
  HttpApiUrl:
    Description: "HTTP API endpoint URL"
    Value:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: HttpApi
          - ".execute-api.${self:provider.region}.amazonaws.com"               
